webtalk_init -webtalk_dir D:/Documents/CMPE 140/cmpe_140-assignment-8/assignment_8/Lab_5.sim/sim_3/behav/xsim/xsim.dir/tb_SOC_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May  5 13:52:31 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c17ca284-bfe8-46e8-9e84-d248475492be" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e490891391e04ac4a8da26862544ebb4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "112" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "41" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "140 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "35 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "618" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "298" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.81_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "57496_KB" -context "xsim\\usage"
webtalk_transmit -clientid 881705643 -regid "" -xml D:/Documents/CMPE 140/cmpe_140-assignment-8/assignment_8/Lab_5.sim/sim_3/behav/xsim/xsim.dir/tb_SOC_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Documents/CMPE 140/cmpe_140-assignment-8/assignment_8/Lab_5.sim/sim_3/behav/xsim/xsim.dir/tb_SOC_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Documents/CMPE 140/cmpe_140-assignment-8/assignment_8/Lab_5.sim/sim_3/behav/xsim/xsim.dir/tb_SOC_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
