@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat May 09 10:55:55 -0700 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_SOC_behav -key {Behavioral:sim_3:Functional:tb_SOC} -tclbatch tb_SOC.tcl -view C:/Users/aliza/Documents/cmpe_140/assignment_8/tb_SOC_behav.wcfg -log simulate.log"
call xsim  tb_SOC_behav -key {Behavioral:sim_3:Functional:tb_SOC} -tclbatch tb_SOC.tcl -view C:/Users/aliza/Documents/cmpe_140/assignment_8/tb_SOC_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
