# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/aliza/Documents/cmpe_140/assignment_8/.Xil/Vivado-2168-LAPTOP-8D7LEK0E/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial {
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/7seg_driver.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/CLA_Adder.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/CarryLookBlock.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/Comparator.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/D_Register.v
      {C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/Factorial Accelerator.v}
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/Factorial.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/Factorial_CU.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/Factorial_DP.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/Gate.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/HalfAdder.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/Hazard_CU.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/Parallel_Multiplier.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/PilelinedProcessor.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/SRLatch.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/XOR.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/datapath/adder.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/datapath/alu.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/control_unit/auxdec.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/basys3_single_cycle_mips_validation/button_debouncer.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/basys3_single_cycle_mips_validation/clk_gen.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/control_unit/controlunit.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/memory/dmem.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/fact_ad.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/gpio.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/gpio_ad.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/basys3_single_cycle_mips_validation/hex_to_7seg.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/memory/imem.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/basys3_single_cycle_mips_validation/led_mux.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/main_ad.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/control_unit/maindec.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/mipsPilelined.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/datapath/mux2.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/datapath/mux4.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/pc_reg_withStall.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/pipelined_DP.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/reg_D.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/reg_E.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/reg_F.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/reg_M.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/datapath/regfile.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/single_cycle_mips_source_initial/datapath/signext.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/soc.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Factorial/up_down_counter.v
      C:/Users/aliza/Documents/cmpe_140/assignment_8/Lab_5.srcs/sources_1/new/fpga_top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top fpga_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/aliza/Documents/cmpe_140/assignment_8/.Xil/Vivado-2168-LAPTOP-8D7LEK0E/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
